### ISSUE TITLE
AWS api calls are throttled when there are too many parallel builds

### ISSUE THREAD

**Issue by uttamk** [awslabs/aws-codebuild-jenkins-plugin#31]
We have around 10 parallel builds per branch/commit triggered from Jenkins. When two or three branches run in parallel, we get 
`Rate exceeded (Service: AWSCodeBuild; Status Code: 400; Error Code: ThrottlingException`
and the build fails.
This is because the CodeBuild plugin polls AWS CodeBuild every 5 seconds. When there are thirty builds in parallel, the number of requests made in a small interval of time is high enough for the AWS api infrastructure to throttle the calls.

**Comment by uttamk** [comment]
##### Proposed solution
Add a `pollingInterval` build parameter to the `CodeBuildStep`. Keep the default to 5 seconds. Let the users decide if they want to increase it to suit their parallelism requirement.

I have a PR for this. See https://github.com/awslabs/aws-codebuild-jenkins-plugin/pull/32

**Comment by oliver-schoenherr** [comment]
The Java AWS SDK includes some Retry Logic concerning ThrottlingExceptions, maybe you should review the default Client Configuration and increase the maxErrorRetry Value.

com.amazonaws.retry.RetryUtils#isThrottlingException

**Comment by uttamk** [comment]
@oliver-schoenherr .. nice suggestion. Do we retry with increasing sleep times after every retry? We need a limit for the number of retries. Do we hard code this in the code or let the plugin have a retries parameter ?

**Comment by oliver-schoenherr** [comment]
The AWS Java SDK includes a Backoff Strategy: 
com.amazonaws.retry.PredefinedRetryPolicies.SDKDefaultBackoffStrategy

*imho* a retry parameter makes no sense from the User Perspective. Maybe this is a major drawback of the solution - because of, normal Plugin User  don't understands the dependency between ThrottlingExceptions and Retry Counts.

You should start with something hardcoded like max 10 Retry.

https://github.com/envato/stack_master/pull/158/commits/12448d8074bd9ed25da57b30c9c8993e91ce553f#diff-1f8a98128798cdf6364b9ebc6358d44fR29

**Comment by uttamk** [comment]
sounds good @oliver-schoenherr. We can start off by hard coding the retry limit/sleep time and see if it works for most use cases. If users need a higher retry limit, we can think about parameterizing the retry limit. 
cc. @leobaran-aws @jvusich any thoughts ?

**Comment by leobaran-aws** [comment]
Sounds good to me! Implementing backoff for build status polling is a great idea.

**Comment by leobaran-aws** [comment]
Merged #35.
