### ISSUE TITLE
Tail cloudwatch logs directly to jenkins

### ISSUE THREAD

**Issue by josegonzalez** [awslabs/aws-codebuild-jenkins-plugin#40]
I've been reading through issues to decide whether we can/should use this plugin, and it appears that we would need to click out to view logs. It would be great if this instead polled for cloudwatch logs and inserted them as they came in - perhaps with some variable polling interval.

This could also be an optional alternative to the current method of just logging the url to jenkins.

**Comment by leobaran-aws** [comment]
That's definitely feasible. I'll add this to our plugin feature requests and let you know when it's completed. Thanks for the feedback!

**Comment by TruffleMuffin** [comment]
I forked this plugin to add this functionality early on. I piped the logs to the console. One thing I would hope you can take into consideration is that the plugin is polling cloud watch and piping the last "page" to the console. In the case of a hanging build (like a really long NPM install) it just repeats that same information over and over again which isn't great.

I think either place would be good to have the 'full log' from cloud watch, but duplication can be problematic in the Console output.

**Comment by josegonzalez** [comment]
If you can poll the cloudwatch output for output since a time/log-line, that will probably suffice for de-duplicating log output.

**Comment by TruffleMuffin** [comment]
It's something I considered, but a number of our builds have very large log files which could lead to a lot of storage required quite quickly. If memory serves, I had to integrate with the "last page" work the AWS team already did, and without refactoring that a lot I couldn't extend the window. I needed to keep my custom version in a place where I could get updates from the team fairly easily so I opted not to do that at first. 

However, it should still be an option here I think. Especially if its replacing the log that plugin stores as that could then just have the whole log once rather than a lot of the log many times.

**Comment by TruffleMuffin** [comment]
The main reason I needed this feature was to view errors - to diagnose why the build failed - without having to go into cloud watch. This is particularly important for me as many developers at my company don't have access to the AWS account where the build server is hosted.

One solution - which admittedly is a half way house - would be to just drastically extend the existing data stored by the plugin so it has several hundred lines. That should be enough to see errors in most build outputs from my experience.

**Comment by leobaran-aws** [comment]
3eb9227de6fef6637bfaa98ed1438400fc5bf8e8
The plugin now displays the entire CloudWatch log for the build in both the CodeBuild dashboard and the console output. I've kept the polling time at 5s, as users running many parallel builds can get throttled if the plugin tries pulling logs any faster.

**Comment by TruffleMuffin** [comment]
Thanks very much @leobaran-aws

**Comment by zeu5** [comment]
Is this default behaviour or a configuration that needs to be turned. I have configured a freestyle project to trigger a CodeBuild but all I can see in the log is a link and the end output. I can't seem to find the configuration as well.

**Comment by TruffleMuffin** [comment]
It is a default behaviour. Is there anything in the code build panel that is linked to from the build page.

If I had to guess, I would say its likely that your Jenkins user in IAM does not have permission to access the logs, or your Jenkins server has a IP whitelist for outbound that does not include appropriate ranges for Cloudwatch.

I have run builds this morning on the latest plugin version and there is output as expected,

**Comment by zeu5** [comment]
```
[AWS CodeBuild Plugin] CodeBuild dashboard: https://ap-southeast-1.console.aws.amazon.com/codebuild/home?region=ap-southeast-1#builds/go-starter-dev:133870dd-d7c8-4afc-9ac3-d30e6182c85a/view/new
[AWS CodeBuild Plugin] CloudWatch dashboard: https://console.aws.amazon.com/cloudwatch/home?region=ap-southeast-1#logEvent:group=/aws/codebuild/go-starter-dev;stream=133870dd-d7c8-4afc-9ac3-d30e6182c85a
[AWS CodeBuild Plugin] Build go-starter-dev:133870dd-d7c8-4afc-9ac3-d30e6182c85a failed
```

As you can see I get two links. Both show the respective logs. The jenkins user has GetLogEvents access on this log group as well. Am I missing any other permission? There has been no source IP restrictions on the resource added.

**Comment by TruffleMuffin** [comment]
Logs are working, you can see here

"[AWS CodeBuild Plugin] Build go-starter-dev:133870dd-d7c8-4afc-9ac3-d30e6182c85a failed"

The the build job failed to start. The logs in Jenkins do not bring in any information not in Cloudwatch, and Codebuild jobs can fail for reasons outside of the build process directly. This is usually due to configuration/ecr/internal failure that happens in steps before 'pre_build' where the logs start to kick in.

Recommend you find your build in Codebuild AWS Console panel and see why it has failed.

**Comment by zeu5** [comment]
Apologies for not providing the full context. There have been about 350 lines of logs generated for the same build and are visible both on the CodeBuild dashboard as well as the CloudWatch logs dashboard. The end result of the build was a failure due to the post_build script. 
```
> Error while executing command: sh build/post_build.sh. Reason: exit status 1 (status code: COMMAND_EXECUTION_ERROR)
Build step 'AWS CodeBuild' changed build result to FAILURE
```
Those are the next two lines of the jenkins output

**Comment by TruffleMuffin** [comment]
That one is trickier :)

It looks like build/post_build.sh is a file that you have created. Exit status 1 usually indicates failure condition in the script being returned to the command prompt.

Since its your script, unless it logs output to the console then Cloudwatch won't see it. You will have to modify your script to find out what is happening if its complex, or if its simple you may need to consider that the container based environment that codebuild runs in often doesn't have all system dependencies (for cli tooling), and has some limits of file system access etc. In either case you will need to fix your script/create a custom container in Amazon ECR that can be used to execute the whole build process.

**Comment by zeu5** [comment]
I am quite aware of the reasons for the build failure and have rectified the same as well. But those 350 lines of logs are what led me to the solution. My problem here is to get those logs reflected on Jenkins as well. I'm faced with the same dilemma of having to not provide access to CloudWatch.

**Comment by zeu5** [comment]
Exactly. These logs are available on both CodeBuild and CloudWatch but not on Jenkins. I'm on Jenkins version **2.107.3** and the latest version of the plugin but this behaviour not reflecting for me.

**Comment by TruffleMuffin** [comment]
I can't think of any reason why that would be the case based on my experience with the plugin.

The AWS team usually work US hours so don't come on till later so perhaps they can provide more help than me. 

Do you get the code build dashboard link from the build page on Jenkins? If so there might be something in there that may help debug the issue. Provided a screenshot of my link for reference.

![image](https://user-images.githubusercontent.com/1841494/40715402-5a611566-63fd-11e8-9edc-1f3cb740c161.png)

**Comment by zeu5** [comment]
Apologies for overlooking that icon. I was expecting the logs in the console output. The logs are available under that link. :) Thank you so much for the time and help.

**Comment by TruffleMuffin** [comment]
That's quite alright, have a good day sir!

**Comment by josegonzalez** [comment]
Note, the closing comment was thus:

> The plugin now displays the entire CloudWatch log for the build in both the CodeBuild dashboard and the console output.

So I'd _also_ expect logs in the console output.

**Comment by leobaran-aws** [comment]
Thanks for letting us know about this. The CodeBuild logs should be available in the default console output--this was verified when I posted a fix and closed the issue earlier. I'm investigating to see if this is specific to the new version of Jenkins.

**Comment by zeu5** [comment]
The logs were not displayed on the console due to the permissions issue. But on the CodeBuild tab within Jenkins each respective log event had an error saying permissions denied. That was the only way I could figure out it was a permissions issue. Once that was fixed logs did appear on the console as well.
