### ISSUE TITLE
Plugin  should download S3 artifacts into jenkins artifact store

### ISSUE THREAD

**Issue by akarnani** [awslabs/aws-codebuild-jenkins-plugin#60]
The plugin is able to detect if s3 artifacts are configured on the codebuild project and display an s3 url.  It would be great if it could just download the artifacts and make them available through the jenkins UI.

**Comment by leobaran-aws** [comment]
Can you point me to any documentation for that? Is it a plugin?

**Comment by akarnani** [comment]
It is core functionality of Jenkins.  You can configure a job to archive certain files or directories in the workspace at the end of the build.

So basically, this plugin would download the artifact(s) into (a user specified) directory in the workspace and jenkins (if configured) would archive those files.

**Comment by Petezah** [comment]
I just happened across this issue and thought I would mention what we do to work around this currently.  We just use the Jenkins Pipeline awsSteps plugin for this.  Something like:

```
def result = awsCodeBuild(…) // your build info within the "..."
def artifactPath = result.getArtifactsLocation().split(':::')[1] // split off the ARN protocol part

// Get relevant path parts
def sepIdx = artifactArn.indexOf("/")
String bucketName = artifactArn[0..sepIdx-1]
String folderPath = artifactArn[sepIdx+1..-1]
withAWS {
            s3Download(
                file:"path/in/your/Jenkins/workspace", 
                bucket: bucketName, 
                path:"$folderPath/", 
                force:true)
    }
```

Then you can do the Jenkins archive artifacts step, or whatever else you want to do.  One caveat I have noticed though: it seems like the s3Download step will fail if it is done on a JNLP slave (haven't tried it on an SSH slave).  So I end up having to make sure I'm on the Master before I do this step. :(  It fails on the slave due to some Java remoting data-marshalling issue with paths.

**Comment by blontic** [comment]
It would be great to have an option to copy the artifact to the Jenkins Workspace instead of having a separate task to copy it from S3 as a later step.

The issue I am having is I copy back the artifact which contains test results so I can display them in Jenkins as a html page. But if a test fails in Codebuild, the plugin will return an error which means I cannot find out what the Codebuild buildId is to look up the artifact from S3.

Maybe even set a variable in Jenkins that contains the Codebuild buildId so if the Codebuild job fails we can still retrieve details about the Codebuild job

**Comment by leobaran-aws** [comment]
@blontic the plugin returns build information in the exception thrown upon build failure. See here for an example: https://github.com/awslabs/aws-codebuild-jenkins-plugin/pull/38

**Comment by AlexChesters** [comment]
We currently work around this by storing CodeBuild artifacts in S3 and then downloading them in the last stage of a Jenkins pipeline
```
always {
      sh "aws s3 cp s3://my-bucket/artifacts/$JOB_NAME/$BUILD_NUMBER results --recursive"
      sh "find -name '*.zip' -exec sh -c 'unzip -d \"\${1%.*}\" \"\$1\"' _ {} \\;"
      // Update timestamps so that Jenkins doesn't moan
      // https://issues.jenkins-ci.org/browse/JENKINS-6268
      sh "find -name 'casper-report.xml' -exec sh -c 'touch \$1' _ {} \\;"
      archiveArtifacts artifacts: "results/**/*.png", allowEmptyArchive: true
      junit "results/**/*.xml"
    }
```

It would be great if the CodeBuild plugin could somehow do this for us 😄

**Comment by vgamz** [comment]
A new version 0.47(commit 4a2f809ed3f19d25fab759c2dd6d3a889457cc42) of the plugin has been released which now gives configuration option to download build artifacts to Jenkins project workspace.
