### ISSUE TITLE
Codebuild plugin sets currentBuild.result = "FAILURE"

### ISSUE THREAD

**Issue by segunolulana** [awslabs/aws-codebuild-jenkins-plugin#70]
Whenever there is a failure in Codebuild, the plugin fails the parent Jenkins build in an unrecoverable manner. My Jenkins pipeline allows specific parts of the pipeline that are flakey builds to be rerun and then pass without rerunning the entire build.

However once currentBuild.result has been set to "failure" already, the whole build can never be set to pass again. Could you send failure status to Jenkins by throwing a exception instead of explicitly setting the build as failure?

This was implemented before [here](https://github.com/awslabs/aws-codebuild-jenkins-plugin/commit/aea76256ea40bbd58bae78514e9b110ebbb5a9d8) but reverted again [here](https://github.com/awslabs/aws-codebuild-jenkins-plugin/commit/77dedc3163eb50f6ba18c03d107e1b007e47f42d)

Thanks

**Comment by leobaran-aws** [comment]
Thanks for your feedback. Since we've received requests for both behaviors, I'll add a flag to specify the pipeline failure mode.

**Comment by Nevvea7** [comment]
+1 to this. In my usecase I'm planning to have a job that puts tests that need to run in a SQS queue, kicks off 30-50 codebuild builds in parallel, and let each of them chomp at the queue. So if some of them fail during setup, but all the tests run on other workers, the parent job should pass. Since each of these workers take about 30min to finish, it's quite costly to have the parent job falsely fail and then need to rerun all of them.

**Comment by leobaran-aws** [comment]
Implemented in f597598303e2cfef97dabd83e57f61aae6969ff0. When the new `exceptionFailureMode` is enabled, you can catch exceptions from `awsCodeBuild` steps like so 
```
try {
  awsCodeBuild ...
} catch (hudson.AbortException ae) {

}
```

**Comment by leobaran-aws** [comment]
This will be released in version `0.38` later today.

**Comment by Nevvea7** [comment]
omg thank you so much! you're a life saver!

**Comment by Nevvea7** [comment]
hey sorry, one more question:
it looks like when the plugin sets the whole build result as FAILURE, it also returns a CodeBuildException which has some useful information about the build. When `exceptionFailureMode` is enabled though since it's just an AbortException this info is lost. Is it possible to keep these Exceptions consistent with build info?

**Comment by leobaran-aws** [comment]
Yeah, it makes sense to keep the pipeline failure behavior in sync and only throw CodeBuildExceptions in that flow. I've updated the logic in 281ca95340cbcee969a8d3bd3e2f0121b71dd74f. I'll release this in version `0.39` sometime this week.
