### ISSUE TITLE
Stopping Jenkins job doesn't stop AWS  CodeBuild buld 

### ISSUE THREAD

**Issue by rvlasyuk** [awslabs/aws-codebuild-jenkins-plugin#8]
If stop Jenkins job with running step "Run build on AWS CodeBuild", AWS CodeBuild build continue working. CloudWatch Logs in Jenkins CodeBuild Dashboard stop showing logs flow.

**Comment by leobaran** [comment]
The plugin doesn't currently support stopping builds. When you stop a build in Jenkins it will continue running on CodeBuild but will be dead from the perspective of your Jenkins server. That's why it doesn't update the CloudWatch logs in Jenkins. The plugin should support stopping builds in the future, but for now you could set a timeout in your build configuration.

**Comment by leobaran-aws** [comment]
I've added this functionality in 8ed40f630d2479b276dac252b4e80464c0793670. Thanks for your patience!
