### ISSUE TITLE
CodeBuild Logs in build.xml

### ISSUE THREAD

**Issue by aliusmiles** [awslabs/aws-codebuild-jenkins-plugin#82]
Plugin is storing CodeBuild logs in `build.xml`, duplicating console log already stored in `log` file. Is there any way to disable that behavior, so logs would be stored only in `log` file?

Excerpt from build.xml:
```
 <CodeBuildAction plugin="aws-codebuild@0.40">
      <build class="flow-build" reference="../../.."/>
      <buildId>test-project:80b1444a-0f6d-4d21-8d25-d02fda80eea7</buildId>
      <logs>
        <string>2019/05/08 13:25:52 Waiting for agent ping
</string>
   ...
    </logs>
```

**Comment by leobaran-aws** [comment]
There currently is not a way to disable this behavior. Build logs are duplicated because the plugin stores them to be displayed in the Jenkins CodeBuild dashboard and outputs them to the Jenkins console log. Do your builds output a lot of logs causing this to fill up your Jenkins instance? If so, we can implement a feature to disable logs in the CodeBuild dashboard. You could also look into adding some build cleanup logic to your Jenkins project.

**Comment by aliusmiles** [comment]
Thanks for the explanation! Such feature would be really useful in our use case (Jenkins on AWS Fargate container).

Currently we are gzipping old builds console logs, but removing/cleaning logs from build.xml would save disk space even more, and we rarely even use CodeBuild dashboard.

In the meantime we were planning to try to remove logs section from build.xml by some scheduled job, that shouldn't case any issues, just an empty logs section in CodeBuild dashboard, right?

**Comment by leobaran-aws** [comment]
I think deleting the entire build.xml will make your builds unviewable in the Jenkins UI. You'll want to just remove everything between `<CodeBuildAction plugin="...">` and `</CodeBuildAction>`. In the meantime we will work on the proper fix.
