### ISSUE TITLE
Compute type is always small

### ISSUE THREAD

**Issue by jreslock-salesforce** [awslabs/aws-codebuild-jenkins-plugin#90]
I've configured my Jenkins instance to use CodeBuild for dynamic build agents.  It seems to work well but I am having an issue with setting the compute type.

The default for this plugin is `small`.  If I use the drop-down to set the compute type to something other than `small` it is always reverted to `small` when I come back into manage jenkins.

CodeBuild plugin version: 0.45
Jenkins version: 2.190.3

Reverting to version 0.44 of the plugin results in the same behavior.

**Comment by leoherran-aws** [comment]
By default, the plugin will use the compute type of the CodeBuild project. The configuration the plugin provides is actually the compute type override, so it should be blank by default. Also, the values should look like `BUILD_GENERAL1_SMALL`. 

Since you mentioned using a dropdown to select the compute type, I'm assuming you are using a freestyle project. Is that correct?

**Comment by jreslock-salesforce** [comment]
Actually this is a multi-branch pipeline.  The drop down is in Manage Jenkins -> System Configuration in "Add a Cloud" -> CodeBuilder: AWS CodeBuild Cloud Agents.

This is so I can give these agents a label and refer to them in the Jenkinsfile's `agent { label 'codebuild' }` and the job automatically fires up an agent.

**Comment by leoherran-aws** [comment]
I think the plugin you are using is [this one](https://github.com/lsegal/jenkins-codebuilder-plugin). This repository is for the AWS-supported CodeBuild Jenkins plugin.

**Comment by jreslock-salesforce** [comment]
You are correct thank you.  I apologize for the confusion.
